### ISSUE TITLE
this workflow can not be import to Alfred 3

### ISSUE THREAD

**Issue by daizy008** [vdesabou/alfred-mac-osx-sharing#1]
can you re-upload it ?

**Comment by vdesabou** [comment]
Hi,

I fixed the download link : https://github.com/vdesabou/alfred-mac-osx-sharing/releases/download/v1.12/alfred-mac-osx-sharing.alfredworkflow

**Comment by daizy008** [comment]
can I share a link by airdrop?
I type share & paste url ,but doesnot find the choose for Airdrop,just fb,tw,message,email.
can you help me？
thank you！

**Comment by vdesabou** [comment]
You can only share files using Airdrop, not text.

There is a File Extension:

![screenshot 2017-03-27 at 17 52 57](https://cloud.githubusercontent.com/assets/4061923/24365454/3e188652-1316-11e7-906d-3e4165814b1a.jpg)

And then once it is selected, you can choose one of the following:

![screenshot 2017-03-27 at 17 51 50](https://cloud.githubusercontent.com/assets/4061923/24365480/5434c810-1316-11e7-935c-4e46873f0a3b.jpg)
